#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"
debug=

if test $# -eq 0 ; then
  mode="h"
fi

while getopts ":fDqh" opt ; do
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  mode="f"
  ;;

D )
  debug="T"
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  mode="q"
  ;;

* )
  mode="h"
  ;;
esac
done

# chop off the commandline parameters parsed above, i.e. keep the user-specified paths
for (( i=OPTIND; i > 1; i-- )) do
  shift
done

if [ $debug ] ; then echo "mode=$mode, debug=$debug, [$#] --> [$@]" ; fi

if test $mode = "h" ; then
  cat <<EOT
$0 [-f] [-F] [-D] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. refresh all submodule remotes: change their access URIs
           when they have changed.
-D       : DEBUG: print extensive debug / progress information.           
-q       : 'quick', i.e. only register all submodule remotes which have not been
           set up yet.

Default behaviour is 'quick mode'.

submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.
	   Specify '.' as the path to match ALL submodules.

EOT
  exit
fi

submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    if [ $debug ] ; then echo "register_remote [$path] [$name] [$repo] [$argc] [...]"; fi
    #if [ $debug ] ; then echo "--> register_remote [$@]"; fi

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if [ $debug ] ; then echo "TEST HIT = $hit --> $( test $hit -ne 0 ; echo $? )" ; fi
    if test $hit -ne 0 ; then
        if [ $debug ] ; then echo "PATH = $path --> $( test -d $path ; echo $? ), $( test -e $path/.git ; echo $? )"; fi
        if test -d $path && test -e $path/.git ; then
            if [ $debug ] ; then echo "ACTION! (mode = $mode)"; fi
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
		if [ $debug ] ; then echo "git remote rm $name"; fi
                git remote rm $name
            fi
            if [ $debug ] ; then echo "git remote add $name $repo"; fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote 0ca_fuzzing_corpus_pdfs                                       0ca                                      https://github.com/0ca/corpus_pdfs.git                                           $# $@
register_remote 0ca_fuzzing_corpus_pdfs                                       0ca-original                             https://github.com/0ca/corpus_pdfs.git                                           $# $@
register_remote 0ca_fuzzing_corpus_pdfs                                       GerHobbelt                               https://github.com/GerHobbelt/corpus_pdfs.git                                    $# $@
register_remote ACL-anthology-corpus                                          GerHobbelt                               https://github.com/GerHobbelt/ACL-anthology-corpus.git                           $# $@
register_remote ACL-anthology-corpus                                          shauryr                                  https://github.com/shauryr/ACL-anthology-corpus.git                              $# $@
register_remote ACL-anthology-corpus                                          shauryr-original                         https://github.com/shauryr/ACL-anthology-corpus.git                              $# $@
register_remote ACL-anthology-corpus                                          zouharvi                                 https://github.com/zouharvi/ACL-anthology-corpus.git                             $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 elliottbolzan                            https://github.com/elliottbolzan/Ariadne.git                                     $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 elliottbolzan-original                   https://github.com/elliottbolzan/Ariadne.git                                     $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 GerHobbelt                               https://github.com/GerHobbelt/Ariadne.git                                        $# $@
register_remote artifex-mupdf-test-corpus                                     artifex-original                         git://git.ghostscript.com/tests.git                                              $# $@
register_remote artifex-mupdf-test-corpus                                     GerHobbelt-original                      https://github.com/GerHobbelt/artifex-mupdf-test-corpus.git                      $# $@
register_remote joris-schellekens-pdf-corpus                                  GerHobbelt                               https://github.com/GerHobbelt/pdf-corpus.git                                     $# $@
register_remote joris-schellekens-pdf-corpus                                  jorissschellekens                        https://github.com/jorisschellekens/pdf-corpus.git                              $# $@
register_remote joris-schellekens-pdf-corpus                                  jorissschellekens-original               https://github.com/jorisschellekens/pdf-corpus.git                              $# $@
register_remote joris-schellekens-pdf-corpus                                  yan01                                    https://github.com/Yan-1-20/pdf-repository.git                                   $# $@
register_remote list-of-other-pdf-corpora-out-there                           GerHobbelt                               https://github.com/GerHobbelt/pdf-corpora.git                                    $# $@
register_remote list-of-other-pdf-corpora-out-there                           pdf-association                          https://github.com/pdf-association/pdf-corpora.git                               $# $@
register_remote list-of-other-pdf-corpora-out-there                           pdf-association-original                 https://github.com/pdf-association/pdf-corpora.git                               $# $@
register_remote openpreserve-format-corpus                                    anjackson                                https://github.com/anjackson/format-corpus.git                                   $# $@
register_remote openpreserve-format-corpus                                    bl4ckic3                                 https://github.com/bl4ckic3/format-corpus.git                                    $# $@
register_remote openpreserve-format-corpus                                    carlwilson                               https://github.com/carlwilson/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    GerHobbelt                               https://github.com/GerHobbelt/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    mistydemeo                               https://github.com/mistydemeo/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    openpreserve                             https://github.com/openpreserve/format-corpus.git                                $# $@
register_remote openpreserve-format-corpus                                    openpreserve-original                    https://github.com/openpreserve/format-corpus.git                                $# $@
register_remote openpreserve-format-corpus                                    sallain                                  https://github.com/sallain/format-corpus.git                                     $# $@
register_remote openpreserve-format-corpus                                    WeAreAVP                                 https://github.com/WeAreAVP/format-corpus.git                                    $# $@
register_remote pdfium_tests                                                  chenjian                                 https://github.com/chenjian-rits/pdfium_tests.git                                $# $@
register_remote pdfium_tests                                                  GerHobbelt                               https://github.com/GerHobbelt/pdfium_tests.git                                   $# $@
register_remote pdfium_tests                                                  pdfium_tests_original                    https://pdfium.googlesource.com/pdfium_tests                                     $# $@
register_remote pdfium_tests                                                  QPDFium                                  https://github.com/QPDFium/pdfium_tests.git                                      $# $@
register_remote veraPDF-corpus                                                DmitryRemezow                            https://github.com/DmitryRemezow/veraPDF-corpus-PDFA-1b.git                      $# $@
register_remote veraPDF-corpus                                                faceless2                                https://github.com/faceless2/veraPDF-corpus.git                                  $# $@
register_remote veraPDF-corpus                                                GerHobbelt                               https://github.com/GerHobbelt/veraPDF-corpus.git                                 $# $@
register_remote veraPDF-corpus                                                nikitakovaliov92                         https://github.com/nikitakovaliov92/veraPDF-corpus.git                           $# $@
register_remote veraPDF-corpus                                                OlgaKostyukovich                         https://github.com/OlgaKostyukovich/veraPDF-corpus.git                           $# $@
register_remote veraPDF-corpus                                                veraPDF                                  https://github.com/veraPDF/veraPDF-corpus.git                                    $# $@
register_remote veraPDF-corpus                                                veraPDF-original                         https://github.com/veraPDF/veraPDF-corpus.git                                    $# $@



popd                                                                            2> /dev/null   > /dev/null

