#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"
debug=

if test $# -eq 0 ; then
  mode="h"
fi

while getopts ":fDqh" opt ; do
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  mode="f"
  ;;

D )
  debug="T"
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  mode="q"
  ;;

* )
  mode="h"
  ;;
esac
done

# chop off the commandline parameters parsed above, i.e. keep the user-specified paths
for (( i=OPTIND; i > 1; i-- )) do
  shift
done

if [ $debug ] ; then echo "mode=$mode, debug=$debug, [$#] --> [$@]" ; fi

if test $mode = "h" ; then
  cat <<EOT
$0 [-f] [-F] [-D] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. refresh all submodule remotes: change their access URIs
           when they have changed.
-D       : DEBUG: print extensive debug / progress information.           
-q       : 'quick', i.e. only register all submodule remotes which have not been
           set up yet.

Default behaviour is 'quick mode'.

submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.
	   Specify '.' as the path to match ALL submodules.

EOT
  exit
fi

submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    if [ $debug ] ; then echo "register_remote [$path] [$name] [$repo] [$argc] [...]"; fi
    #if [ $debug ] ; then echo "--> register_remote [$@]"; fi

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if [ $debug ] ; then echo "TEST HIT = $hit --> $( test $hit -ne 0 ; echo $? )" ; fi
    if test $hit -ne 0 ; then
        if [ $debug ] ; then echo "PATH = $path --> $( test -d $path ; echo $? ), $( test -e $path/.git ; echo $? )"; fi
        if test -d $path && test -e $path/.git ; then
            if [ $debug ] ; then echo "ACTION! (mode = $mode)"; fi
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
		if [ $debug ] ; then echo "git remote rm $name"; fi
                git remote rm $name
            fi
            if [ $debug ] ; then echo "git remote add $name $repo"; fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote 0ca_fuzzing_corpus_pdfs                                       0ca                                      https://github.com/0ca/corpus_pdfs.git                                           $# $@
register_remote 0ca_fuzzing_corpus_pdfs                                       0ca-original                             https://github.com/0ca/corpus_pdfs.git                                           $# $@
register_remote 0ca_fuzzing_corpus_pdfs                                       GerHobbelt                               https://github.com/GerHobbelt/corpus_pdfs.git                                    $# $@
register_remote ACL-anthology-corpus                                          GerHobbelt                               https://github.com/GerHobbelt/ACL-anthology-corpus.git                           $# $@
register_remote ACL-anthology-corpus                                          shauryr                                  https://github.com/shauryr/ACL-anthology-corpus.git                              $# $@
register_remote ACL-anthology-corpus                                          shauryr-original                         https://github.com/shauryr/ACL-anthology-corpus.git                              $# $@
register_remote ACL-anthology-corpus                                          zouharvi                                 https://github.com/zouharvi/ACL-anthology-corpus.git                             $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 elliottbolzan                            https://github.com/elliottbolzan/Ariadne.git                                     $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 elliottbolzan-original                   https://github.com/elliottbolzan/Ariadne.git                                     $# $@
register_remote Ariadne-LinearA-Minoan-corpus                                 GerHobbelt                               https://github.com/GerHobbelt/Ariadne.git                                        $# $@
register_remote artifex-mupdf-test-corpus                                     artifex-original                         git://git.ghostscript.com/tests.git                                              $# $@
register_remote artifex-mupdf-test-corpus                                     GerHobbelt-original                      https://github.com/GerHobbelt/artifex-mupdf-test-corpus.git                      $# $@
register_remote joris-schellekens-pdf-corpus                                  GerHobbelt                               https://github.com/GerHobbelt/pdf-corpus.git                                     $# $@
register_remote joris-schellekens-pdf-corpus                                  jorisschellekens                         https://github.com/jorisschellekens/pdf-corpus.git                               $# $@
register_remote joris-schellekens-pdf-corpus                                  jorissschellekens                        https://github.com/jorisschellekens/pdf-corpus.git                               $# $@
register_remote joris-schellekens-pdf-corpus                                  jorissschellekens-original               https://github.com/jorisschellekens/pdf-corpus.git                               $# $@
register_remote joris-schellekens-pdf-corpus                                  yan01                                    https://github.com/Yan-1-20/pdf-repository.git                                   $# $@
register_remote list-of-other-pdf-corpora-out-there                           GerHobbelt                               https://github.com/GerHobbelt/pdf-corpora.git                                    $# $@
register_remote list-of-other-pdf-corpora-out-there                           pdf-association                          https://github.com/pdf-association/pdf-corpora.git                               $# $@
register_remote list-of-other-pdf-corpora-out-there                           pdf-association-original                 https://github.com/pdf-association/pdf-corpora.git                               $# $@
register_remote openpreserve-format-corpus                                    anjackson                                https://github.com/anjackson/format-corpus.git                                   $# $@
register_remote openpreserve-format-corpus                                    bl4ckic3                                 https://github.com/bl4ckic3/format-corpus.git                                    $# $@
register_remote openpreserve-format-corpus                                    carlwilson                               https://github.com/carlwilson/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    GerHobbelt                               https://github.com/GerHobbelt/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    mistydemeo                               https://github.com/mistydemeo/format-corpus.git                                  $# $@
register_remote openpreserve-format-corpus                                    openpreserve                             https://github.com/openpreserve/format-corpus.git                                $# $@
register_remote openpreserve-format-corpus                                    openpreserve-original                    https://github.com/openpreserve/format-corpus.git                                $# $@
register_remote openpreserve-format-corpus                                    sallain                                  https://github.com/sallain/format-corpus.git                                     $# $@
register_remote openpreserve-format-corpus                                    thorsted                                 https://github.com/thorsted/format-corpus.git                                    $# $@
register_remote openpreserve-format-corpus                                    WeAreAVP                                 https://github.com/WeAreAVP/format-corpus.git                                    $# $@
register_remote pdf2htmlEX-testcases                                          coolwanglu                               https://github.com/coolwanglu/pdf2htmlEX-testcase.git                            $# $@
register_remote pdf2htmlEX-testcases                                          GerHobbelt                               https://github.com/GerHobbelt/pdf2htmlEX-testcase.git                            $# $@
register_remote pdfium_tests                                                  chenjian                                 https://github.com/chenjian-rits/pdfium_tests.git                                $# $@
register_remote pdfium_tests                                                  chenjian-rits                            https://github.com/chenjian-rits/pdfium_tests.git                                $# $@
register_remote pdfium_tests                                                  GerHobbelt                               https://github.com/GerHobbelt/pdfium_tests.git                                   $# $@
register_remote pdfium_tests                                                  pdfium_tests_original                    https://pdfium.googlesource.com/pdfium_tests                                     $# $@
register_remote pdfium_tests                                                  QPDFium                                  https://github.com/QPDFium/pdfium_tests.git                                      $# $@
register_remote pdfminer-testcases                                            apollo13                                 https://github.com/apollo13/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            aremus85                                 https://github.com/aremus85/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            arpitjain799                             https://github.com/arpitjain799/pdfminer.six.git                                 $# $@
register_remote pdfminer-testcases                                            Artoria2e5                               https://github.com/Artoria2e5/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            attestivJ                                https://github.com/attestivJ/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            BradenM                                  https://github.com/BradenM/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            building-estimates                       https://github.com/building-estimates/pdfminer.six.git                           $# $@
register_remote pdfminer-testcases                                            ciupicri                                 https://github.com/ciupicri/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            cjmayo                                   https://github.com/cjmayo/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            claasz                                   https://github.com/claasz/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            crisptag                                 https://github.com/crisptag/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            dalaomai                                 https://github.com/dalaomai/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            datamade                                 https://github.com/datamade/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            deathadderclicker                        https://github.com/deathadderclicker/pdfminer.six.git                            $# $@
register_remote pdfminer-testcases                                            dmlls                                    https://github.com/dmlls/pdfminer.six.git                                        $# $@
register_remote pdfminer-testcases                                            dntjr970                                 https://github.com/dntjr970/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            dwittal                                  https://github.com/dwittal/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            edugonza                                 https://github.com/edugonza/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            ehtec                                    https://github.com/ehtec/pdfminer.six.git                                        $# $@
register_remote pdfminer-testcases                                            fgregg                                   https://github.com/fgregg/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            FieteO                                   https://github.com/FieteO/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            goingforbrooke                           https://github.com/goingforbrooke/pdfminer.six.git                               $# $@
register_remote pdfminer-testcases                                            gosiafilipek                             https://github.com/gosiafilipek/pdfminer.six.git                                 $# $@
register_remote pdfminer-testcases                                            HiTalentAlgorithms                       https://github.com/HiTalentAlgorithms/pdfminer.six.git                           $# $@
register_remote pdfminer-testcases                                            htInEdin                                 https://github.com/htInEdin/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            InscribeAI                               https://github.com/InscribeAI/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            instabase                                https://github.com/instabase/pdfminer.six.public.git                             $# $@
register_remote pdfminer-testcases                                            it-brasil                                https://github.com/it-brasil/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            jangxyz                                  https://github.com/jangxyz/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            jjbiggins                                https://github.com/jjbiggins/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            jlemke                                   https://github.com/jlemke/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            johnwalz97                               https://github.com/johnwalz97/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            josiahkhor                               https://github.com/josiahkhor/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            jsvine                                   https://github.com/jsvine/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            juliagauch                               https://github.com/juliagauch/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            JulianFeinauer                           https://github.com/JulianFeinauer/pdfminer.six.git                               $# $@
register_remote pdfminer-testcases                                            jwyawney                                 https://github.com/jwyawney/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            kash203                                  https://github.com/kash203/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            kinoute                                  https://github.com/kinoute/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            knowron                                  https://github.com/knowron/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            kumapo                                   https://github.com/kumapo/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            KunalGehlot                              https://github.com/KunalGehlot/pdfminer.six.git                                  $# $@
register_remote pdfminer-testcases                                            lbuchli                                  https://github.com/lbuchli/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            lDisciple                                https://github.com/lDisciple/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            leo-prnd                                 https://github.com/leo-prnd/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            LexPredict                               https://github.com/LexPredict/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            Mana-bio                                 https://github.com/Mana-bio/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            MapleCCC                                 https://github.com/MapleCCC/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            Mause                                    https://github.com/Mause/pdfminer.six.git                                        $# $@
register_remote pdfminer-testcases                                            muriloime                                https://github.com/muriloime/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            nathtest                                 https://github.com/nathtest/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            NAZADOTH                                 https://github.com/NAZADOTH/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            nexus-lib                                https://github.com/nexus-lib/pdfminer.six.cython.git                             $# $@
register_remote pdfminer-testcases                                            NiteshOswal                              https://github.com/NiteshOswal/pdfminer.six.git                                  $# $@
register_remote pdfminer-testcases                                            one-leaf                                 https://github.com/one-leaf/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            pdfminer                                 https://github.com/pdfminer/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            pedrounes1                               https://github.com/pedrounes1/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            perceptionpoint                          https://github.com/perceptionpoint/pdfminer.six.git                              $# $@
register_remote pdfminer-testcases                                            pettzilla1                               https://github.com/pettzilla1/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            phantomcyber                             https://github.com/phantomcyber/pdfminer.six.git                                 $# $@
register_remote pdfminer-testcases                                            power-zhy                                https://github.com/power-zhy/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            qued                                     https://github.com/qued/pdfminer.six.git                                         $# $@
register_remote pdfminer-testcases                                            revacprogramming                         https://github.com/revacprogramming/pdfminer.six.git                             $# $@
register_remote pdfminer-testcases                                            ricardocarvalhods                        https://github.com/ricardocarvalhods/pdfminer.six.git                            $# $@
register_remote pdfminer-testcases                                            richardpaulhudson                        https://github.com/richardpaulhudson/pdfminer.six.git                            $# $@
register_remote pdfminer-testcases                                            rkasperski                               https://github.com/rkasperski/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            rmbittmann                               https://github.com/rmbittmann/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            SEKOIA-IO                                https://github.com/SEKOIA-IO/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            sheldonldev                              https://github.com/sheldonldev/pdfminer.six.git                                  $# $@
register_remote pdfminer-testcases                                            shriya3099                               https://github.com/shriya3099/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            sobuen                                   https://github.com/sobuen/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            sthenault                                https://github.com/sthenault/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            sudodoki                                 https://github.com/sudodoki/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            syabyr                                   https://github.com/syabyr/pdfminer.six.git                                       $# $@
register_remote pdfminer-testcases                                            TheMcSebi                                https://github.com/TheMcSebi/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            tianzhipengfei                           https://github.com/tianzhipengfei/pdfminer.six.git                               $# $@
register_remote pdfminer-testcases                                            Tiger-lok                                https://github.com/Tiger-lok/pdfminer.six.git                                    $# $@
register_remote pdfminer-testcases                                            tongbaojia                               https://github.com/tongbaojia/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            vargenau                                 https://github.com/vargenau/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            venidera                                 https://github.com/venidera/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            vigenere92                               https://github.com/vigenere92/pdfminer.six.git                                   $# $@
register_remote pdfminer-testcases                                            vijuc895                                 https://github.com/vijuc895/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            vilabho                                  https://github.com/vilabho/pdfminer.six.git                                      $# $@
register_remote pdfminer-testcases                                            weartist                                 https://github.com/weartist/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            wind-chh                                 https://github.com/wind-chh/pdfminer.six.git                                     $# $@
register_remote pdfminer-testcases                                            wpm                                      https://github.com/wpm/pdfminer.six.git                                          $# $@
register_remote pdfminer-testcases                                            yusithiesun                              https://github.com/yusithiesun/pdf2json.git                                      $# $@
register_remote pdfminer-testcases                                            zypriafl                                 https://github.com/zypriafl/pdfminer.six.git                                     $# $@
register_remote veraPDF-corpus                                                DmitryRemezow                            https://github.com/DmitryRemezow/veraPDF-corpus-PDFA-1b.git                      $# $@
register_remote veraPDF-corpus                                                faceless2                                https://github.com/faceless2/veraPDF-corpus.git                                  $# $@
register_remote veraPDF-corpus                                                georgetarazevich                         https://github.com/georgetarazevich/veraPDF-corpus.git                           $# $@
register_remote veraPDF-corpus                                                GerHobbelt                               https://github.com/GerHobbelt/veraPDF-corpus.git                                 $# $@
register_remote veraPDF-corpus                                                nikitakovaliov92                         https://github.com/nikitakovaliov92/veraPDF-corpus.git                           $# $@
register_remote veraPDF-corpus                                                OlgaKostyukovich                         https://github.com/OlgaKostyukovich/veraPDF-corpus.git                           $# $@
register_remote veraPDF-corpus                                                veraPDF                                  https://github.com/veraPDF/veraPDF-corpus.git                                    $# $@
register_remote veraPDF-corpus                                                veraPDF-original                         https://github.com/veraPDF/veraPDF-corpus.git                                    $# $@



popd                                                                            2> /dev/null   > /dev/null

